spring.application.name=pims

spring.datasource.url=jdbc:postgresql://postgres-db:5432/pims_db
spring.datasource.username=ikos_admin
spring.datasource.password=admin_password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect